### ISSUE TITLE
Create first API test

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/PetStoreAPITesting#1]
1. Add required dependencies like rest assured
2. Write simple API tests: POST and GET for https://petstore.swagger.io/#/pet
See examples of tests: https://github.com/topsycreed/unitTestsGradle/blob/master/src/test/java/SimpleAPITests.java or in RestAssured docs
You can try to create and get data about pet or user using swagger manual firstlty and then automate such scenario.

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/PetStoreAPITesting/pull/2
