### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/PetStoreAPITesting#8]
Update Readme file with description of the project and instructions how to run it. See examples:

1. https://github.com/basdijkstra/rest-assured-workshop
2. https://github.com/VladaDanilova/imdb-ui
3. https://github.com/KorolevaEka/final-diplom
And overall profile: https://github.com/KorolevaEka and https://github.com/basdijkstra

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/PetStoreAPITesting/pull/9
